# Generated by Django 5.2.6 on 2025-09-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quizlink',
            name='questions',
            field=models.ManyToManyField(related_name='quiz_links', through='quiz.QuizQuestion', to='quiz.question'),
        ),
    ]
