# Generated by Django 5.2.6 on 2025-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_question_image_path_quizlink_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="source",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
