# Generated by Django 4.1 on 2024-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_student_quizlink_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="disabled_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
