# Generated by Django 4.1 on 2025-12-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_test_question_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionFeedback',
            fields=[
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz.quizquestion',),
        ),
    ]
