# Generated by Django 4.1 on 2026-09-19 11:46

import django.core.validators
from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quizquestionfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlink',
            name='academic_year',
            field=models.CharField(default='2025_26', max_length=7, validators=[django.core.validators.RegexValidator('\\A[0-9]{4}_[0-9]{2}\\Z', 'Use YYYY_YY, for example 2026_27.')]),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(default='2025_26', max_length=7, validators=[django.core.validators.RegexValidator('\\A[0-9]{4}_[0-9]{2}\\Z', 'Use YYYY_YY, for example 2026_27.')]),
        ),
        migrations.AddField(
            model_name='test',
            name='academic_year',
            field=models.CharField(default='2025_26', max_length=7, validators=[django.core.validators.RegexValidator('\\A[0-9]{4}_[0-9]{2}\\Z', 'Use YYYY_YY, for example 2026_27.')]),
        ),
        migrations.AlterField(
            model_name='quizlink',
            name='academic_year',
            field=models.CharField(db_index=True, default=quiz.models.default_academic_year, max_length=7, validators=[django.core.validators.RegexValidator(r'\A[0-9]{4}_[0-9]{2}\Z', 'Use YYYY_YY, for example 2026_27.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(db_index=True, default=quiz.models.default_academic_year, max_length=7, validators=[django.core.validators.RegexValidator(r'\A[0-9]{4}_[0-9]{2}\Z', 'Use YYYY_YY, for example 2026_27.')]),
        ),
        migrations.AlterField(
            model_name='test',
            name='academic_year',
            field=models.CharField(db_index=True, default=quiz.models.default_academic_year, max_length=7, validators=[django.core.validators.RegexValidator(r'\A[0-9]{4}_[0-9]{2}\Z', 'Use YYYY_YY, for example 2026_27.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('email', 'academic_year'), name='student_email_academic_year'),
        ),
    ]
